<?php

namespace AppBundle\Repository;

/**
 * DessertmenumillesabordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DessertmenumillesabordsRepository extends \Doctrine\ORM\EntityRepository
{
}
