<?php

namespace AppBundle\Repository;

/**
 * MenumenumillesabordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenumenumillesabordsRepository extends \Doctrine\ORM\EntityRepository
{
}
