<?php

namespace AppBundle\Repository;

/**
 * PizzamenumillesabordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzamenumillesabordsRepository extends \Doctrine\ORM\EntityRepository
{
}
