<?php

namespace AppBundle\Repository;

/**
 * PlatmenumillesabordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatmenumillesabordsRepository extends \Doctrine\ORM\EntityRepository
{
}
